{% set name = "pandas-datapackage-reader" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8bcef889f8e2b867ad8ea1602b4d81c40c330d1e81f9ba794eb2755ba026bad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pandas
    - requests

test:
  imports:
    - pandas_datapackage_reader

  commands: python -c "import pandas_datapackage_reader; assert pandas_datapackage_reader.__version__ == '{{ version }}'"

about:
  home: https://github.com/rgieseke/pandas-datapackage-reader
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Data Package reader for Pandas
  doc_url: https://github.com/rgieseke/pandas-datapackage-reader/blob/master/README.md
  dev_url: https://github.com/rgieseke/pandas-datapackage-reader

extra:
  recipe-maintainers:
    - znicholls
    - rgieseke
