travis:
  secure:
    BINSTAR_TOKEN: I4ZcRB+uTXughKdWdYUVsxv7iW6/YI7d0iZLAFbG2/Qb/dXr3AQtRQiFNKyYc/Ug0jaeuE8Tpvqy1M+2xV3I0bDn2CCQ7Zte9Qiue7/Fzs5AOnJzBmUTSdafLCKI1E0iSs2UlSgtL30z/PIfMWIiZxOmS/o5jniyXeglHS9woK+rmiyW9qXqmuDWKBgsLn7A98RLTbcvTd28bUN0LMREH9CwP2UGk/RNFqknTonk5Cn9zzh7IAGClSi5BN4rnqiEvL3+0tPVmeFDfjE90oTHJZACLggjU1BtW7ok7/ctLhYk3NXgKN18Coda6uKuF3z/B+CDYIVY4R22n4LXMLmo5HuNxlTElcaJDTq9fp3bRSMp+6FFOkBOJUPWW3J1raaL3xnsLk8QKtE5060yb2XWvz4yUebzG8FuTGP83NKM0/xKmJ3lvyCe2nFhrESDgNTmEzUn1s2oJVzNfWIv8ttZ5zwQxW68QLVn1riCSOLQ2xu0hQuuFg1KFPn+bd3cxZEz141HB+ke1w1GHqigmBqLdMDu6OFJQ3M/nH42md30uy5E0hmfcaazav+nMu5dZahLkBh7LFmPfGrnSuRDam4/VdzEiAsHDbSiHPTun9sCsnLOInkj4kC+bUIvP7Z7fwrBQkjkmuzDUTbKyb2wbY04zWtfoh7RiGZScB6qRuKKBIc=
conda_forge_output_validation: true
bot:
  automerge: true
